
SCHEMA_DEFINITIONS = """
create table public.supplier_analysis (
  full_option_code character varying(17) not null,
  location character(3) not null,
  location_name character varying(60) not null,
  service character(2) not null,
  supplier character(6) not null,
  destination_code character(3) not null,
  destination_description character varying(60) not null,
  code character(6) not null,
  supplier_name character varying(60) not null,
  description character varying(60) not null,
  comment character varying(60) not null,
  class character(3) not null,
  opt_id integer not null,
  oie text null,
  oif text null,
  ois text null,
  oii text null,
  one text null,
  oni text null,
  ong text null,
  onf text null,
  ons text null,
  ode text null,
  odi text null,
  odg text null,
  odf text null,
  ods text null,
  odb text null,
  agr text null,
  oig text null,
  pickup character varying(3) not null,
  dropoff character varying(3) not null,
  pickup_points character varying(256) null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  is_deleted boolean null default false,
  constraint supplier_analysis_pkey primary key (full_option_code)
) TABLESPACE pg_default;

create table public.products (
  id_num integer null,
  code character(6) not null,
  location_code character(3) not null,
  description character varying(60) not null,
  description_alt character varying(60) not null,
  service_code public.product_service_enum not null,
  internet_option character(1) not null,
  supplier_code character(6) not null,
  comment character varying(60) not null,
  comment_alt character varying(60) not null,
  is_deleted_flag boolean not null,
  location_name character varying(60) not null,
  locality_code public.product_locality_enum null,
  class_code public.product_class_enum null,
  rate_id integer null,
  rate_date_to timestamp without time zone null,
  rate_buy_currency public.currency_enum null,
  rate_sell_currency public.currency_enum null,
  rate_price_code public.product_rate_price_enum null,
  paxd_id integer null,
  paxd_rate_type public.product_paxd_rate_enum null,
  type_code public.service_product_type_enum not null,
  analysis1_code character(2) not null,
  analysis1_name character(60) not null,
  analysis2_code character(2) not null,
  analysis2_name character(60) not null,
  analysis3_code character(2) not null,
  analysis3_name character(60) not null,
  analysis4_code character(2) not null,
  analysis4_name character(60) not null,
  analysis5_code character(2) not null,
  analysis5_name character(60) not null,
  analysis6_code character(2) not null,
  analysis6_name character(60) not null,
  id text not null,
  full_option_code character varying null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  is_deleted boolean null default false,
  constraint products_pkey primary key (id)
) TABLESPACE pg_default;

create table public.proveedurias (
  id bigint not null,
  proveeduria_group text null,
  name text not null,
  tourplan boolean null,
  codigo_proveedor_tp text null,
  expedia_taap boolean null,
  disponibilidad_tp_status text null,
  item_id_column bigint null,
  surges boolean null,
  anp_status text null,
  carpeta_proveedor text null,
  creation_log text null,
  rp_completo boolean null,
  ultima_actualizacion_rp date null,
  impacto_status text null,
  bedsonline boolean null,
  anual_tarifas_status text null,
  tarifas_2025_tp boolean null,
  _2026_producto_status text null,
  _2026_sistemas_status text null,
  tarifas_2026_button text null,
  margen_promedio numeric(6, 2) null,
  tipo_servicio text null,
  categoria text null,
  rango_precios smallint null,
  state_tags text null,
  locations text null,
  localities text null,
  ubicacion text null,
  pu_url_maps text null,
  garantia_reservacion_status text null,
  email_reservas text null,
  otros_contactos text null,
  contacto_reservaciones text null,
  telefono_reservas text null,
  abrir_whatsapp_reservas text null,
  contacto_operaciones text null,
  telefono_ops text null,
  abrir_whatsapp_ops text null,
  contacto_comercial text null,
  convenio_acuerdo_status text null,
  tipo_factura_raiz_status text null,
  tarifa_en_tp_status text null,
  notas_datos_bancarios text null,
  alta_banco boolean null,
  banco_status text null,
  titular_cuenta text null,
  clabe text null,
  correo_comprobante_pago text null,
  tarjeta text null,
  cuenta text null,
  consulta_usd_mxn_status text null,
  servicios_2024 numeric null,
  monto_venta_2024 numeric(14, 2) null,
  servicios_2025 numeric null,
  monto_venta_2025 numeric(14, 2) null,
  servicios_2026 numeric null,
  monto_venta_2026 numeric(14, 2) null,
  cotizado_2024 text null,
  cotizado_2025_2026 text null,
  horario_desayuno text null,
  estacionamiento_status text null,
  delighters boolean null,
  etiquetas text null,
  grupo_impacto text null,
  politica_edades text null,
  tipo_alojamiento text null,
  instalaciones_servicios text null,
  num_habitaciones text null,
  alimentos_disponibles text null,
  proceso_producto_status text null,
  reputacion_online_status text null,
  fuente_status text null,
  _2025_producto_status text null,
  _2025_sistemas_status text null,
  tiempo_respuesta_status text null,
  disponibilidad_bloqueo_status text null,
  registro_creacion text null,
  fecha_integracion date null,
  tiempo_en_dias text null,
  idiomas text null,
  resp_guias_people text null,
  sincronizado_text text null,
  prov_potenciales_status text null,
  status_rutobot text null,
  ruto_academia_status text null,
  incidencias_item_ids bigint[] null,
  grupo_wa_link text null,
  tipo_factura_raiz_2_status text null,
  control_calidad_item_ids bigint[] null,
  seguros boolean null,
  last_updated_at timestamp with time zone null,
  actitud_personal_numero_mirror text null,
  formulario_hoteles_item_ids text null,
  reflejo_mirror text null,
  fecha_recepcion_tarifas_2026 date null,
  fecha_subida_tarifas_2026_tp date null,
  proveedor_codigo text not null,
  updated_at timestamp without time zone null default now(),
  constraint proveedurias_pkey primary key (id, proveedor_codigo)
) TABLESPACE pg_default;

create table public.inventario_turistico (
  id bigint not null,
  inventario_turistico_group text not null,
  name text not null,
  location text null,
  service text null,
  supplier text null,
  code text null,
  description text null,
  class text null,
  creation text null,
  descriptives text null,
  pictures text null,
  new_note text null,
  subelements text null,
  provider text null,
  language text null,
  ideal_for text null,
  topic text null,
  proveeduria bigint null,
  proveeduria_group text null,
  nombre_carpeta_producto text null,
  nombre_experiencia text null,
  codigo_madre text null,
  nombre_carpeta_proveedor text null,
  board_name text null,
  creation_log timestamp with time zone null,
  updated_at timestamp without time zone null default now(),
  constraint inventario_turistico_pkey primary key (id)
) TABLESPACE pg_default;

create table public.experiences (
  id uuid not null default gen_random_uuid (),
  narrative_text text null,
  service_type text null,
  destination_name text null,
  supplier_name text null,
  pricing_year text null,
  tariff_process text null,
  location_address text null,
  city text null,
  availability_response_time text null,
  min_adult_age double precision null,
  max_adult_age double precision null,
  min_child_age double precision null,
  max_child_age double precision null,
  min_infant_age double precision null,
  max_infant_age double precision null,
  full_json jsonb null,
  tourplan_id text null,
  created_at timestamp with time zone null default now(),
  vector_embedding public.vector null,
  duration real null,
  lon double precision null,
  lat double precision null,
  constraint experiences_pkey primary key (id)
) TABLESPACE pg_default;

create table public.lodging (
  id uuid not null default gen_random_uuid (),
  tourplan_id text not null,
  narrative_text text null,
  accommodation_type text null,
  available_food text null,
  facilities_services text null,
  num_rooms text null,
  location_address text null,
  city text null,
  google_maps_url text null,
  available_days text null,
  availability_response_time text null,
  min_adult_age double precision null,
  max_adult_age double precision null,
  min_child_age double precision null,
  max_child_age double precision null,
  min_infant_age double precision null,
  max_infant_age double precision null,
  tags text null,
  full_json jsonb null,
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  vector_embedding public.vector null,
  destination_name text null,
  price_range text null,
  has_parking boolean null,
  supplier_name text null,
  breakfast_hours text null,
  lat double precision null,
  lon double precision null,
  geom geometry null,
  king_beds smallint null,
  queen_beds smallint null,
  double_beds smallint null,
  single_beds smallint null,
  bunk_beds smallint null,
  sofa_beds smallint null,
  total_sleep_capacity smallint null,
  constraint lodging_pkey primary key (id)
) TABLESPACE pg_default;

create table public.transport (
  id uuid not null default gen_random_uuid (),
  tourplan_id text not null,
  narrative_text text null,
  service_type text null,
  service_description text null,
  duration text null,
  full_service_description text null,
  service_notes text null,
  destination_name text null,
  location_address text null,
  city text null,
  google_maps_url text null,
  available_days text null,
  availability_response_time text null,
  min_adult_age double precision null,
  max_adult_age double precision null,
  min_child_age double precision null,
  max_child_age double precision null,
  min_infant_age double precision null,
  max_infant_age double precision null,
  max_persons double precision null,
  tags text null,
  pricing_year text null,
  tariff_status text null,
  product_ready text null,
  supplier_name text null,
  supplier_group text null,
  full_json jsonb null,
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  vector_embedding public.vector null,
  origin_lat double precision null,
  origin_lon double precision null,
  destination_lat double precision null,
  destination_lon double precision null,
  transport_capacity integer null default 0,
  vehicle_type text null,
  max_passengers integer null,
  service_class text null,
  constraint transport_pkey primary key (id)
) TABLESPACE pg_default;

create table public.tariff_person_group (
  full_option_code character varying(17) not null,
  location character(3) not null,
  name character varying(60) not null,
  service character(2) not null,
  service_type character varying(60) not null,
  supplier character(6) not null,
  supplier_name character varying(60) not null,
  code character(6) not null,
  description character varying(60) not null,
  comment character varying(60) not null,
  fcu character(6) not null,
  scu character(6) not null,
  class character(3) not null,
  int_option character(1) not null,
  opt_id integer not null,
  maximum_persons numeric(12, 4) not null,
  price_code character(2) not null,
  date_from timestamp without time zone not null,
  date_to timestamp without time zone not null,
  stay_type character varying(60) not null,
  rate_text character varying(60) not null,
  min_scu integer not null,
  ratest character varying(9) null,
  infant_from integer not null,
  infant_to integer not null,
  child_from integer not null,
  child_to integer not null,
  adult_from integer not null,
  adult_to integer not null,
  buy_currency character(3) not null,
  sell_currency character(3) not null,
  destination_code character(3) not null,
  destination_description character varying(60) not null,
  apply_for_monday character varying(3) null,
  apply_for_tuesday character varying(3) null,
  apply_for_wednesday character varying(3) null,
  apply_for_thursday character varying(3) null,
  apply_for_friday character varying(3) null,
  apply_for_saturday character varying(3) null,
  apply_for_sunday character varying(3) null,
  servitem character varying(70) null,
  costgroups numeric(18, 4) not null,
  markup_margen_groups numeric(19, 4) null,
  markupporc_groups numeric(40, 21) null,
  margenporc_groups numeric(40, 21) null,
  sellgroups numeric(18, 4) not null,
  costfits numeric(18, 4) not null,
  markup_margen_fits numeric(19, 4) null,
  markupporc_fits numeric(40, 21) null,
  margenporc_fits numeric(40, 21) null,
  fitsell numeric(18, 4) not null,
  sellfits numeric(18, 4) not null,
  id text not null,
  constraint tariff_person_group_pkey primary key (id),
  constraint tariff_person_group_full_option_code_fkey foreign KEY (full_option_code) references supplier_analysis (full_option_code)
) TABLESPACE pg_default;
"""
